import styled from 'styled-components'

export const PayWrapper = styled.div`
    height:${window.innerHeight}px;
    width:${window.innerWidth}px;
    background-image:url('/images/paybj.jpg');
    background-size:cover;
    display:flex;
    flex-direction:column;
    .payContent{
        height:60%;
        width:100&;
        display:flex;
        justify-content:center;
        align-items:center;
        .payContentWrap{
            height:50%;
            width:80%;
            background:rgba(255,255,255,0.5);
            .payTitle{
                width:100%;
                height:30%;
                display:flex;
                justify-content:center;
                align-items:center;
                font-size:20px;
                font-weight:bold;
            }
            .payMoney{
                width:100%;
                height:40%;
                font-size:30px;
                display:flex;
                justify-content:center;
                align-items:center;
            }
            .payState{
                width:100%;
                height:30%;
                display:flex;
                justify-content:center;
                align-items:center;
                .payBtn{
                    height:50px;
                    width:80%;
                    background:skyblue;
                    border-radius:10px;
                    font-size:18px;
                    color:#fff;
                    display:flex;
                    justify-content:center;
                    align-items:center;
                }
            }
        }
    }
    .payFinger{
        height:40%;
        width:100&;
        display:flex;
        justify-content:center;
        align-items:center;
        .imgBox{
            height:100px;
            width:100px;
            :active{
                background:rgba(255,255,255,0.5);
            }
            img{
                height:100%;
                width:100%;
            }
        }
        
    }
`