export const GET_LIST_ASYNC = 'GET_LIST_ASYNC'
export const GET_ISSHOWING_LIST = 'GET_ISSHOWING_LIST'
export const GET_SOONSHOWING_LIST = 'GET_SOONSHOWING_LIST'
export const GET_CINEMAS_LIST = 'GET_CINEMAS_LIST'

